USE tmart;

DROP TABLE if EXISTS customers;

CREATE TABLE customers(
  customer_id INT AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(50) NOT NULL,
  last_name VARCHAR(50) NOT NULL,
  gender CHAR(1) DEFAULT NULL,
  phone_number VARCHAR(12) DEFAULT NULL,
  email VARCHAR(255) DEFAULT NULL,
  address VARCHAR(200) DEFAULT NULL,
  city VARCHAR(100) DEFAULT NULL,
  state CHAR(2) DEFAULT NULL,
  zipcode VARCHAR(10) DEFAULT NULL,
  county VARCHAR(50) DEFAULT NULL,
  dob DATE DEFAULT NULL,
  is_active TINYINT,
  loyalty_memeber TINYINT DEFAULT NULL,
  date_created datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  date_inactive datetime DEFAULT NULL,
  date_updated datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = INNODB DEFAULT CHARSET = UTF8MB4;